server:
    port: 8662

spring:
    application:
        name: web-gis-application-zuul-proxy

eureka:
  client:
      registerWithEureka: true
      fetchRegistry: true
      serviceUrl:
          defaultZone: http://localhost:8661/eureka
  instance:
      hostname: localhost

zuul:
    host:
        connect-timeout-millis: 5000000
        socket-timeout-millis: 5000000
    ignoredServices: '*'
    routes:
        resource-service:
            path: /api/**
            serviceId: web-gis-application-feign-client
            stripPrefix: true
        user-service:
            path: /repository/**
            serviceId: web-gis-client-repository
            stripPrefix: true


