ribbon:
  ConnectTimeout: 120000
  ReadTimeout: 120000

#Application
server:
  port: 8662
spring:
  application:
    name: web-gis-application-zuul-proxy

#Eureka
eureka:
  client:
    registerWithEureka: true
    fetchRegistry: true
    serviceUrl:
      defaultZone: http://ec2-13-59-137-49.us-east-2.compute.amazonaws.com:8661/eureka
  instance:
    hostname: localhost

#Zuul Proxy
zuul:
  host:
    time-to-live: -1
    connect-timeout-millis: 50000
    max-per-route-connections: 100000
    max-total-connections: 50000
    socket-timeout-millis: 600000
    semaphore:
      max-semaphores: 5000
  ignoredServices: '*'
  routes:
    geo-tools-resource-service:
      path: /api/geo-tools/**
      serviceId: web-gis-application-feign-client-geo-tools
      stripPrefix: true
    resource-service:
      path: /api/**
      serviceId: web-gis-application-feign-client
      stripPrefix: true
    user-service:
      path: /repository/**
      serviceId: web-gis-client-repository
      stripPrefix: true
    geo-tools-user-service:
      path: /geo-tools/**
      serviceId: web-gis-client-geo-tools
      stripPrefix: true