#Application
server:
  port: 8662
spring:
  application:
    name: web-gis-application-zuul-proxy

#Eureka
eureka:
  client:
    registerWithEureka: true
    fetchRegistry: true
    serviceUrl:
      defaultZone: http://localhost:8661/eureka
  instance:
    hostname: localhost

#Zuul Proxy
zuul:
  host:
    connect-timeout-millis: 5000000
    socket-timeout-millis: 5000000
  ignoredServices: '*'
  routes:
    geo-tools-resource-service:
      path: /api/geo-tools/**
      serviceId: web-gis-application-feign-client-geo-tools
      stripPrefix: true
    resource-service:
      path: /api/**
      serviceId: web-gis-application-feign-client
      stripPrefix: true
    user-service:
      path: /repository/**
      serviceId: web-gis-client-repository
      stripPrefix: true
    geo-tools-user-service:
      path: /geo-tools/**
      serviceId: web-gis-client-geo-tools
      stripPrefix: true